hill_cmsccbl_homepage:
    pattern:  /home
    defaults: { _controller: HillCMSCCBLBundle:Default:index }
login:
    pattern:   /login
    defaults:  { _controller: HillCMSSecurityBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern: /logout
