parameters:
#    hill_cmsccbl.example.class: HillCMS\CCBLBundle\Example

services:
#    hill_cmsccbl.example:
#        class: %hill_cmsccbl.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
