parameters:
#    hill_cms_security.example.class: HillCMS\SecurityBundle\Example

services:
#    hill_cms_security.example:
#        class: %hill_cms_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
