parameters:
#    hill_cms_spirodela.example.class: HillCMS\SpirodelaBundle\Example

services:
#    hill_cms_spirodela.example:
#        class: %hill_cms_spirodela.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
