manage:
    pattern: /manage
    defaults: { _controller: HillCMSManageBundle:Default:index}
save:
    pattern: /manage/save
    defaults: {_controller: HillCMSManageBundle:Default:save} 
success:
    pattern: /manage
    defaults: {_controller:HillCMSManageBundle:Default:index}
adduser:
    pattern: /manage/adduser
    defaults: {_controller:HillCMSManageBundle:Default:adduser}
saverole:
    pattern: /manage/saverole
    defaults: {_controller: HillCMSManageBundle:Default:saverole}
